import 'package:flutter/material.dart';

class AppData {
  final List categories = [
    "Transportation",
    'Travel',
    'Food and Groceries',
    'Healthcare',
    'Self Care',
    'Housing or Rent',
    "Entertainment",
    'Emergency Fund',
    'Insurance',
    'Debt Payment',
    'Clothing',
    'Groceriese',
    'Investors',
    'Personal Care',
    'Savings',
    'Internet',
    'Phone',
    'Eating Out',
    'Shopping',
    'Car Payment',
    'Education',
    'Entertainment',
    'Gas',
    'Water',
    'Child Care',
    'Memberships and Subscription',
    'Pet Food Care',
    'Electricity',
    'Cell Phone',
    'Miscellanious',
    'Housing',
    'Rent or Mortgage',
    'Property Taxes',
    'Home Insurance',
    'Utilities',
    'Electricity',
    'Water',
    'Gas',
    'Internet',
    'Maintenance and Repairs',
    'Car Payments',
    'Fuel',
    'Car Insurance',
    'Public Transportation',
    'Groceries',
    'Dining Out',
    'Coffee and Snacks',
    'Health Insurance Premiums',
    'Doctor Visits',
    'Medications',
    'Dental Care',
    'Vision Care',
    'Life Insurance',
    'Disability Insurance',
    'Other Insurance Policies',
    'Credit Card Payments',
    'Student Loan Payments',
    'Personal Loan Payments',
    'Cable/Satellite TV',
    'Movies',
    'Streaming Services',
    'Hobbies',
    'Concerts and Events',
    'Haircuts',
    'Beauty Products',
    'Gym Memberships',
    'Apparel Purchases',
    'Shoes and Accessories',
    'Tuition',
    'Books and Supplies',
    'Emergency Fund Contributions',
    'Retirement Savings',
    'Birthday and Holiday Gifts',
    'Charitable Donations',
    'Income Taxes',
    'Property Taxes',
    'Daycare',
    'Babysitting',
    'Other Uncategorized Expenses',
  ];
  Map listIcon = {
    "Transportation": Icons.directions_car,
    'Travel': Icons.airplanemode_active,
    'Food and Groceries': Icons.local_grocery_store,
    'Healthcare': Icons.local_hospital,
    'Self Care': Icons.spa,
    'Memberships and Subscription': Icons.subscriptions,
    'Housing or Rent': Icons.home,
    'Entertainment': Icons.movie,
    'Emergency Fund': Icons.warning,
    'Insurance': Icons.assignment,
    'Debt Payment': Icons.payment,
    'Clothing': Icons.shopping_bag,
    'Groceriese': Icons.local_grocery_store,
    'Investors': Icons.attach_money,
    'Personal Care': Icons.person,
    'Savings': Icons.account_balance,
    'Internet': Icons.wifi,
    'Phone': Icons.phone,
    'Eating Out': Icons.restaurant,
    'Shopping': Icons.shopping_cart,
    'Car Payment': Icons.directions_car,
    'Education': Icons.school,
    'Gas': Icons.local_gas_station,
    'Water': Icons.opacity,
    'Child Care': Icons.child_care,
    'Pet Food Care': Icons.pets,
    'Electricity': Icons.electrical_services,
    'Cell Phone': Icons.phone_android,
    'Miscellanious': Icons.category,
    'Rent or Mortgage': Icons.home,
    'Property Taxes': Icons.account_balance,
    'Home Insurance': Icons.home,
    'Utilities': Icons.settings,
    'Maintenance and Repairs': Icons.build,
    'Car Payments': Icons.directions_car,
    'Fuel': Icons.local_gas_station,
    'Car Insurance': Icons.assignment,
    'Public Transportation': Icons.directions_bus,
    'Dining Out': Icons.restaurant,
    'Coffee and Snacks': Icons.local_cafe,
    'Health Insurance Premiums': Icons.local_hospital,
    'Doctor Visits': Icons.local_hospital,
    'Medications': Icons.medical_services,
    'Dental Care': Icons.local_hospital,
    'Vision Care': Icons.visibility,
    'Life Insurance': Icons.assignment,
    'Disability Insurance': Icons.assignment,
    'Other Insurance Policies': Icons.assignment,
    'Credit Card Payments': Icons.credit_card,
    'Student Loan Payments': Icons.school,
    'Personal Loan Payments': Icons.payment,
    'Cable/Satellite TV': Icons.live_tv,
    'Movies': Icons.movie,
    'Streaming Services': Icons.smart_display,
    'Hobbies': Icons.sports_esports,
    'Concerts and Events': Icons.event,
    'Beauty Products': Icons.spa,
    'Gym Memberships': Icons.fitness_center,
    'Apparel Purchases': Icons.shopping_bag,
    'Shoes and Accessories': Icons.shopping_bag,
    'Tuition': Icons.school,
    'Books and Supplies': Icons.menu_book,
    'Emergency Fund Contributions': Icons.warning,
    'Retirement Savings': Icons.account_balance,
    'Birthday and Holiday Gifts': Icons.card_giftcard,
    'Charitable Donations': Icons.volunteer_activism,
    'Income Taxes': Icons.account_balance,
    'Daycare': Icons.child_care,
    'Babysitting': Icons.child_friendly,
    'Other Uncategorized Expenses': Icons.category,
  };
  Map months = {
    "January": "1",
    "February": "2",
    "March": "3",
    "April": "4",
    "May": "5",
    "June": "6",
    "July": "7",
    "August": "8",
    "September": "9",
    "October": "10",
    "November": "11",
    "December": "12",
  };
  Map intTomonths = {
    "1": "January",
    "2": "February",
    "3": "March",
    "4": "April",
    "5": "May",
    "6": "June",
    "7": "July",
    "8": "August",
    "9": "September",
    "10": "October",
    "11": "November",
    "12": "December",
  };
  year() {
    List years = [];
    for (int i = 2000; i <= DateTime.now().year; i++) {
      years.add(i);
    }
    return years;
  }
}
